function [fitresult, gof] = createFit(V, D)
%CREATEFIT(V,D)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: D
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-May-2023 03:15:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, D );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );

legend( h(2), 'Fitted curve', 'Location', 'NorthEast', 'Interpreter', 'none','FontSize' ,12 );
% Label axes
xlabel( 'Volume fraction %', 'Interpreter', 'none' );
ylabel('Largsest minimnum distance (mm)' );

dim = [0.44 0.49 0.4 0.34];
str = {'Fitted model (x) = 1.14x^2 - 3.56x + 7.61','R^2=  0.934'};
annotation('textbox',dim,'String',str,'FitBoxToText','on','LineWidth', 0.1);
grid off


